//! `nexus shadow on|ai|nexus|off|status` — hide agentic scaffold files from Git.
//!
//! Since ADR-0125 (NEXUS-APP dispatch 15497fa2) the shadow level is a
//! project setting on the server (`policy.shadow`: `off` | `ai` | `nexus`)
//! and `nexus shadow` is a thin client of it: it sets the level, then
//! applies the server's `af_export.git_exclude` list as a managed block in
//! `.git/info/exclude` (local, never committed). `nexus pull` applies the
//! same block on every run. Files already tracked in git are never
//! untracked automatically; a `git rm -r --cached` hint is printed instead.
//!
//! Backends without `policy.shadow` (or an unlinked workspace) keep the
//! old local mode: `on` adds a fixed pattern block and untracks matching
//! files without history, `off` removes it and re-adds them.

use std::fs;
use std::path::{Path, PathBuf};
use std::process::Command;

use console::style;

// ---------------------------------------------------------------------------
// Agentic file patterns to shadow
// ---------------------------------------------------------------------------

/// Files and directories generated by AI coding agents / agentic tooling.
const AGENTIC_PATTERNS: &[&str] = &[
    // Claude Code / Anthropic
    ".claude/",
    "CLAUDE.md",
    // OpenCode
    ".opencode/",
    "opencode.json",
    "opencode.jsonc",
    // Nexus
    ".nexus/",
    "AGENTS.md",
    // Cursor
    ".cursorrules",
    ".cursorignore",
    // Kiro
    ".kiro/",
    // Roo
    ".roo/",
    ".roomodes",
    // Windsurf
    ".windsurfrules",
    // GitHub Copilot
    ".github/copilot-instructions.md",
    // Taskmaster AI
    ".taskmaster/",
    "taskmaster.config.yaml",
    "tasks/",
    ".taskmasterconfig",
    // RTK
    ".rtk/",
    "RTK.md",
];

/// Workspace file patterns to shadow (devbox/workspace stack).
const WORKSPACE_PATTERNS: &[&str] = &["devbox.json", "devbox.lock", ".devbox/", "scripts/devbox/"];

/// Marker comments used to delimit our block in .git/info/exclude.
const MARKER_START: &str = "# >>> nexus shadow";
const MARKER_END: &str = "# <<< nexus shadow";

/// Marker comments for workspace shadow block.
const WS_MARKER_START: &str = "# >>> nexus workspace shadow";
const WS_MARKER_END: &str = "# <<< nexus workspace shadow";

// ---------------------------------------------------------------------------
// Public entry points — agentic shadow
// ---------------------------------------------------------------------------

/// Enable shadow mode (agentic files).
pub fn on() -> anyhow::Result<()> {
    let git_dir = find_git_dir()?;
    let exclude_path = git_dir.join("info").join("exclude");

    // Ensure .git/info/ exists
    if let Some(parent) = exclude_path.parent() {
        fs::create_dir_all(parent)?;
    }

    // Check if already active
    if is_block_active(&exclude_path, MARKER_START) {
        println!(
            "{} Shadow mode is already enabled.",
            style("●").green().bold()
        );
        return Ok(());
    }

    // Build and write the exclude block
    write_exclude_block(&exclude_path, MARKER_START, MARKER_END, AGENTIC_PATTERNS)?;

    // Remove already-tracked files from the index (best effort)
    let removed = untrack_patterns(AGENTIC_PATTERNS)?;

    println!(
        "{} Shadow mode {}.",
        style("●").green().bold(),
        style("enabled").green().bold()
    );
    println!(
        "  {} agentic patterns added to .git/info/exclude",
        AGENTIC_PATTERNS.len()
    );
    if removed > 0 {
        println!(
            "  {} previously tracked file(s) removed from index (files kept on disk)",
            removed
        );
    }
    println!(
        "  {}",
        style("Note: .git/info/exclude is local and will not be committed.").dim()
    );

    Ok(())
}

/// Disable shadow mode (agentic files).
pub fn off() -> anyhow::Result<()> {
    let git_dir = find_git_dir()?;
    let exclude_path = git_dir.join("info").join("exclude");

    if !is_block_active(&exclude_path, MARKER_START) {
        println!("{} Shadow mode is not currently enabled.", style("○").dim());
        return Ok(());
    }

    // Remove our block from the exclude file
    let content = fs::read_to_string(&exclude_path)?;
    let cleaned = remove_block(&content, MARKER_START, MARKER_END);
    fs::write(&exclude_path, &cleaned)?;

    // Re-track files that exist on disk (best effort)
    let re_added = retrack_patterns(AGENTIC_PATTERNS)?;

    println!(
        "{} Shadow mode {}.",
        style("○").yellow().bold(),
        style("disabled").yellow().bold()
    );
    println!("  Agentic patterns removed from .git/info/exclude");
    if re_added > 0 {
        println!("  {} file(s) re-added to Git tracking", re_added);
    }

    Ok(())
}

/// Show current shadow mode status (agentic files).
pub fn status() -> anyhow::Result<()> {
    local_status(false)
}

/// The local blocks. With `server_level` the server decides the agentic
/// excludes, so the local agentic block is labelled as the legacy mode
/// instead of reading like a contradiction to the server level.
fn local_status(server_level: bool) -> anyhow::Result<()> {
    let git_dir = find_git_dir()?;
    let exclude_path = git_dir.join("info").join("exclude");

    let agentic_active = is_block_active(&exclude_path, MARKER_START);
    let workspace_active = is_block_active(&exclude_path, WS_MARKER_START);
    let workspace_label = if server_level {
        "Workspace shadow (devbox files)"
    } else {
        "Workspace shadow"
    };

    if server_level {
        if agentic_active {
            println!(
                "{} Local shadow block (legacy): {}",
                style("●").yellow().bold(),
                style("active").yellow().bold()
            );
            println!("  Shadowed patterns:");
            for pat in AGENTIC_PATTERNS {
                println!("    {}", style(pat).dim());
            }
        } else {
            println!(
                "{} Local shadow block (legacy): {}",
                style("○").dim(),
                style("none").dim()
            );
        }
    } else if agentic_active {
        println!(
            "{} Shadow mode is {}.",
            style("●").green().bold(),
            style("enabled").green().bold()
        );
        println!("  Shadowed patterns:");
        for pat in AGENTIC_PATTERNS {
            println!("    {}", style(pat).dim());
        }
    } else {
        println!(
            "{} Shadow mode is {}.",
            style("○").dim(),
            style("disabled").dim()
        );
    }

    if workspace_active {
        println!(
            "{} {workspace_label} is {}.",
            style("●").magenta().bold(),
            style("enabled").magenta().bold()
        );
        println!("  Workspace patterns:");
        for pat in WORKSPACE_PATTERNS {
            println!("    {}", style(pat).dim());
        }
    } else {
        println!(
            "{} {workspace_label} is {}.",
            style("○").dim(),
            style("disabled").dim()
        );
    }

    Ok(())
}

// ---------------------------------------------------------------------------
// Public entry points — workspace shadow
// ---------------------------------------------------------------------------

/// Enable workspace shadow mode (devbox files excluded from git).
pub fn workspace_on() -> anyhow::Result<()> {
    let git_dir = find_git_dir()?;
    let exclude_path = git_dir.join("info").join("exclude");

    if let Some(parent) = exclude_path.parent() {
        fs::create_dir_all(parent)?;
    }

    if is_block_active(&exclude_path, WS_MARKER_START) {
        println!(
            "{} Workspace shadow is already enabled.",
            style("●").magenta().bold()
        );
        return Ok(());
    }

    write_exclude_block(
        &exclude_path,
        WS_MARKER_START,
        WS_MARKER_END,
        WORKSPACE_PATTERNS,
    )?;
    let removed = untrack_patterns(WORKSPACE_PATTERNS)?;

    println!(
        "{} Workspace shadow {}.",
        style("●").magenta().bold(),
        style("enabled").magenta().bold()
    );
    println!(
        "  {} workspace patterns added to .git/info/exclude",
        WORKSPACE_PATTERNS.len()
    );
    if removed > 0 {
        println!(
            "  {} previously tracked file(s) removed from index (files kept on disk)",
            removed
        );
    }
    println!(
        "  {}",
        style("Note: .git/info/exclude is local and will not be committed.").dim()
    );

    Ok(())
}

/// Disable workspace shadow mode.
pub fn workspace_off() -> anyhow::Result<()> {
    let git_dir = find_git_dir()?;
    let exclude_path = git_dir.join("info").join("exclude");

    if !is_block_active(&exclude_path, WS_MARKER_START) {
        println!(
            "{} Workspace shadow is not currently enabled.",
            style("○").dim()
        );
        return Ok(());
    }

    let content = fs::read_to_string(&exclude_path)?;
    let cleaned = remove_block(&content, WS_MARKER_START, WS_MARKER_END);
    fs::write(&exclude_path, &cleaned)?;

    let re_added = retrack_patterns(WORKSPACE_PATTERNS)?;

    println!(
        "{} Workspace shadow {}.",
        style("○").yellow().bold(),
        style("disabled").yellow().bold()
    );
    println!("  Workspace patterns removed from .git/info/exclude");
    if re_added > 0 {
        println!("  {} file(s) re-added to Git tracking", re_added);
    }

    Ok(())
}

/// Check whether workspace shadow is currently active.
#[allow(dead_code)]
pub fn is_workspace_shadow_active() -> anyhow::Result<bool> {
    let git_dir = find_git_dir()?;
    let exclude_path = git_dir.join("info").join("exclude");
    Ok(is_block_active(&exclude_path, WS_MARKER_START))
}

/// Ensure that the given file paths are listed in `.git/info/exclude`.
///
/// This is a best-effort operation: if no `.git` directory is found or the
/// exclude file cannot be written, errors are silently ignored. The function
/// is intended to protect token-bearing config files from accidental commit.
pub fn ensure_git_excluded(paths: &[&str]) {
    let Ok(cwd) = std::env::current_dir() else {
        return;
    };
    ensure_git_excluded_in(&cwd, paths, "token-bearing files");
}

/// [`ensure_git_excluded`] for the repository containing `start`, with the
/// reason shown in the comment line above the added entries.
pub fn ensure_git_excluded_in(start: &Path, paths: &[&str], reason: &str) {
    let git_dir = match find_git_dir_from(start.to_path_buf()) {
        Ok(d) => d,
        Err(_) => return,
    };
    let exclude_path = git_dir.join("info").join("exclude");

    // Ensure parent directory exists
    if let Some(parent) = exclude_path.parent() {
        let _ = fs::create_dir_all(parent);
    }

    let existing = fs::read_to_string(&exclude_path).unwrap_or_default();

    let mut additions = Vec::new();
    for path in paths {
        if !existing.lines().any(|line| line.trim() == *path) {
            additions.push(*path);
        }
    }

    if additions.is_empty() {
        return;
    }

    let mut content = existing;
    if !content.ends_with('\n') && !content.is_empty() {
        content.push('\n');
    }
    content.push_str(&format!("# nexus: {reason} (auto-added)\n"));
    for path in additions {
        content.push_str(path);
        content.push('\n');
    }
    let _ = fs::write(&exclude_path, content);
}

// ---------------------------------------------------------------------------
// Server-driven exclude block (ADR-0125, NEXUS-APP dispatch 15497fa2)
// ---------------------------------------------------------------------------

/// Marker comments for the block holding `af_export.git_exclude`.
const SERVER_MARKER_START: &str = "# >>> nexus managed exclude (server)";
const SERVER_MARKER_END: &str = "# <<< nexus managed exclude (server)";

/// What [`apply_server_excludes`] changed.
#[derive(Debug, Default, Clone, PartialEq, Eq)]
pub struct ServerExcludeReport {
    /// Paths newly written to the managed block.
    pub added: Vec<String>,
    /// Paths dropped from the block (the server no longer sends them).
    pub removed: Vec<String>,
    /// Paths refused as unsafe (absolute, `..`, negation, comments).
    pub rejected: Vec<String>,
    /// Excluded paths that git still tracks (an exclude does not untrack).
    pub tracked: Vec<String>,
}

/// Whether a server-sent exclude entry is a plain relative path pattern.
/// Refuses anything that could change the meaning of the exclude file or
/// point outside the repository: empty, absolute, `..` segments, line
/// breaks, negation (`!`) and comments (`#`).
pub fn valid_exclude_path(path: &str) -> bool {
    let p = path.trim();
    !p.is_empty()
        && !p.contains(['\n', '\r', '\\'])
        && !p.starts_with(['/', '!', '#'])
        && !p.split('/').any(|seg| seg == "..")
        && !(p.len() > 1 && p.as_bytes()[1] == b':')
}

/// Entries of a marker-delimited block.
fn block_entries(content: &str, marker_start: &str, marker_end: &str) -> Vec<String> {
    let mut inside = false;
    let mut entries = Vec::new();
    for line in content.lines() {
        let line = line.trim();
        if line == marker_start {
            inside = true;
        } else if line == marker_end {
            inside = false;
        } else if inside && !line.is_empty() && !line.starts_with('#') {
            entries.push(line.to_string());
        }
    }
    entries
}

/// Rewrite the managed block in `.git/info/exclude` of the repository
/// containing `workspace` so it holds exactly the valid `paths` not already
/// listed elsewhere in the file (an empty list removes the block), and
/// report which excluded paths git still tracks. Best effort: outside a git
/// repository, or when the file cannot be written, nothing happens.
pub fn apply_server_excludes(workspace: &Path, paths: &[String]) -> ServerExcludeReport {
    let mut report = ServerExcludeReport::default();
    let Ok(git_dir) = find_git_dir_from(workspace.to_path_buf()) else {
        return report;
    };
    let exclude_path = git_dir.join("info").join("exclude");
    let existing = fs::read_to_string(&exclude_path).unwrap_or_default();
    let previous = block_entries(&existing, SERVER_MARKER_START, SERVER_MARKER_END);
    let outside = remove_block(&existing, SERVER_MARKER_START, SERVER_MARKER_END);

    let mut valid: Vec<String> = Vec::new();
    for raw in paths {
        let p = raw.trim().to_string();
        if !valid_exclude_path(&p) {
            report.rejected.push(raw.clone());
        } else if !valid.contains(&p) {
            valid.push(p);
        }
    }
    let wanted: Vec<String> = valid
        .iter()
        .filter(|p| !outside.lines().any(|l| l.trim() == p.as_str()))
        .cloned()
        .collect();

    report.added = wanted
        .iter()
        .filter(|p| !previous.contains(p))
        .cloned()
        .collect();
    report.removed = previous
        .iter()
        .filter(|p| !wanted.contains(p))
        .cloned()
        .collect();

    let mut content = outside;
    if !wanted.is_empty() {
        if !content.is_empty() && !content.ends_with("\n\n") {
            content.push('\n');
        }
        content.push_str(SERVER_MARKER_START);
        content.push('\n');
        for p in &wanted {
            content.push_str(p);
            content.push('\n');
        }
        content.push_str(SERVER_MARKER_END);
        content.push('\n');
    }
    if content != existing {
        if let Some(parent) = exclude_path.parent() {
            let _ = fs::create_dir_all(parent);
        }
        if fs::write(&exclude_path, &content).is_err() {
            return ServerExcludeReport {
                rejected: report.rejected,
                ..Default::default()
            };
        }
    }

    let workdir = git_dir.parent().unwrap_or(workspace);
    report.tracked = valid
        .iter()
        .filter(|p| !resolve_tracked_paths_in(p.trim_end_matches('/'), Some(workdir)).is_empty())
        .cloned()
        .collect();
    report
}

/// Print what [`apply_server_excludes`] did (pull and `nexus shadow`).
pub fn print_server_exclude_report(report: &ServerExcludeReport, shadow: Option<&str>) {
    let level = shadow
        .filter(|l| !l.is_empty())
        .map(|l| format!(" (shadow: {l})"))
        .unwrap_or_default();
    if !report.added.is_empty() || !report.removed.is_empty() {
        println!(
            "   {} .git/info/exclude: +{}/-{} server path(s){}",
            style("~").bold().cyan(),
            report.added.len(),
            report.removed.len(),
            level
        );
    }
    for path in &report.rejected {
        println!(
            "   {} ignored unsafe exclude entry from the server: {:?}",
            style("!").bold().yellow(),
            path
        );
    }
    for path in &report.tracked {
        println!(
            "   {} {} is excluded but still tracked by git; untrack it with: git rm -r --cached {}",
            style("!").bold().yellow(),
            path,
            path.trim_end_matches('/')
        );
    }
}

/// The server exclude block's entries for the repository containing
/// `workspace` (for `nexus shadow status`).
pub fn server_exclude_entries(workspace: &Path) -> Vec<String> {
    find_git_dir_from(workspace.to_path_buf())
        .ok()
        .and_then(|g| fs::read_to_string(g.join("info").join("exclude")).ok())
        .map(|c| block_entries(&c, SERVER_MARKER_START, SERVER_MARKER_END))
        .unwrap_or_default()
}

/// Map a `nexus shadow` subcommand to a `policy.shadow` value
/// (`on` = `ai`).
pub fn policy_value(action: &str) -> Option<&'static str> {
    match action {
        "on" | "ai" => Some("ai"),
        "nexus" => Some("nexus"),
        "off" => Some("off"),
        _ => None,
    }
}

/// `nexus shadow on|ai|nexus|off`: set `policy.shadow` on the server and
/// apply the resulting `git_exclude` list now. Falls back to the local
/// mode when the workspace is not linked or the backend has no
/// `policy.shadow` setting.
pub async fn set_level(api_url: &str, action: &str, assume_yes: bool) -> anyhow::Result<()> {
    let level =
        policy_value(action).ok_or_else(|| anyhow::anyhow!("unknown shadow level '{action}'"))?;
    if !super::env_cmd::has_setting(api_url, "policy.shadow")
        .await
        .unwrap_or(false)
    {
        println!(
            "   {} No server shadow setting (workspace not linked or backend without policy.shadow); using local shadow mode.",
            style("i").bold().blue()
        );
        return if level == "off" { off() } else { on() };
    }

    super::env_cmd::set(api_url, "policy.shadow", level, false, assume_yes).await?;
    let workspace = std::env::current_dir()?;
    let (project_id, client) = super::env_cmd::connect(api_url)?;
    let export = client.export_agent_files(&project_id).await?;
    let report = apply_server_excludes(&workspace, &export.git_exclude);
    print_server_exclude_report(&report, export.shadow.as_deref());

    // The old local block would keep hiding the agentic files.
    if level == "off" {
        let exclude_path = find_git_dir_from(workspace)?.join("info").join("exclude");
        if is_block_active(&exclude_path, MARKER_START) {
            let content = fs::read_to_string(&exclude_path)?;
            fs::write(
                &exclude_path,
                remove_block(&content, MARKER_START, MARKER_END),
            )?;
            println!(
                "   {} removed the local shadow block from .git/info/exclude (files stay untracked; git add them if wanted)",
                style("~").bold().cyan()
            );
        }
    }
    println!(
        "{} Shadow level {}.",
        style("●").green().bold(),
        style(level).bold()
    );
    Ok(())
}

/// `nexus shadow status`: the server level and its exclude block, then the
/// local blocks.
pub async fn status_with_server(api_url: &str) -> anyhow::Result<()> {
    let workspace = std::env::current_dir()?;
    let mut server_level = false;
    if let Ok((project_id, client)) = super::env_cmd::connect(api_url) {
        match client.export_agent_files(&project_id).await {
            Ok(export) => {
                server_level = export.shadow.is_some();
                let level = export
                    .shadow
                    .as_deref()
                    .unwrap_or("not set (older backend)");
                println!(
                    "{} Server shadow level: {}",
                    style("●").cyan().bold(),
                    style(level).bold()
                );
                let entries = server_exclude_entries(&workspace);
                if entries.is_empty() {
                    println!(
                        "  {}",
                        style("No server exclude block (run nexus pull).").dim()
                    );
                } else {
                    println!("  Server exclude block:");
                    for e in entries {
                        println!("    {}", style(e).dim());
                    }
                }
            }
            Err(e) => println!(
                "{} Server shadow level unavailable: {}",
                style("○").dim(),
                e
            ),
        }
    }
    local_status(server_level)
}

// ---------------------------------------------------------------------------
// Helpers
// ---------------------------------------------------------------------------

/// Find the `.git` directory by walking up from CWD.
fn find_git_dir() -> anyhow::Result<PathBuf> {
    find_git_dir_from(std::env::current_dir()?)
}

/// Find the `.git` directory by walking up from `dir`.
fn find_git_dir_from(mut dir: PathBuf) -> anyhow::Result<PathBuf> {
    loop {
        let candidate = dir.join(".git");
        if candidate.is_dir() {
            return Ok(candidate);
        }
        if !dir.pop() {
            anyhow::bail!("Not inside a Git repository. Run this command from a Git working tree.");
        }
    }
}

/// Check whether a marker block is present in the exclude file.
fn is_block_active(exclude_path: &Path, marker_start: &str) -> bool {
    if !exclude_path.exists() {
        return false;
    }
    match fs::read_to_string(exclude_path) {
        Ok(content) => content.contains(marker_start),
        Err(_) => false,
    }
}

/// Remove a marker-delimited block from file content.
fn remove_block(content: &str, marker_start: &str, marker_end: &str) -> String {
    let mut result = String::with_capacity(content.len());
    let mut inside_block = false;

    for line in content.lines() {
        if line.trim() == marker_start {
            inside_block = true;
            continue;
        }
        if line.trim() == marker_end {
            inside_block = false;
            continue;
        }
        if !inside_block {
            result.push_str(line);
            result.push('\n');
        }
    }

    let trimmed = result.trim_end_matches('\n');
    if trimmed.is_empty() {
        String::new()
    } else {
        format!("{trimmed}\n")
    }
}

/// Write a marker-delimited exclude block to the exclude file.
fn write_exclude_block(
    exclude_path: &Path,
    marker_start: &str,
    marker_end: &str,
    patterns: &[&str],
) -> anyhow::Result<()> {
    let mut block = String::new();
    block.push('\n');
    block.push_str(marker_start);
    block.push('\n');
    for pat in patterns {
        block.push_str(pat);
        block.push('\n');
    }
    block.push_str(marker_end);
    block.push('\n');

    let mut existing = if exclude_path.exists() {
        fs::read_to_string(exclude_path)?
    } else {
        String::new()
    };
    existing.push_str(&block);
    fs::write(exclude_path, &existing)?;
    Ok(())
}

/// Run `git rm --cached` for each pattern that is currently tracked.
///
/// Skips any file that has a commit history on the current branch
/// (`git log -1 -- <file>` returns output). Removing such a file from the
/// index would stage a deletion that could be accidentally committed.
///
/// Skipped files are reported as warnings so the user can act manually
/// with `git rm --cached` if that is truly their intent.
fn untrack_patterns(patterns: &[&str]) -> anyhow::Result<usize> {
    let mut count = 0;
    for pat in patterns {
        let clean = pat.trim_end_matches('/');

        // Collect concrete paths matched by this pattern (handles dirs and globs).
        let matched_paths = resolve_tracked_paths(clean);

        for path in &matched_paths {
            if is_file_tracked_in_history(path) {
                eprintln!(
                    "  {} skipping '{}' — file has commit history on this branch (use 'git rm --cached {}' manually if intended)",
                    console::style("warning:").yellow().bold(),
                    path,
                    path,
                );
                continue;
            }

            let output = Command::new("git")
                .args(["rm", "-r", "--cached", "--ignore-unmatch", path])
                .output();
            if let Ok(o) = output {
                if o.status.success() {
                    let stdout = String::from_utf8_lossy(&o.stdout);
                    count += stdout.lines().filter(|l| !l.is_empty()).count();
                }
            }
        }

        // Also attempt the pattern itself for any unmatched cases (directories, etc.)
        // that resolve_tracked_paths may have missed — but only if no specific paths
        // were found (avoids double-processing).
        if matched_paths.is_empty() {
            let output = Command::new("git")
                .args(["rm", "-r", "--cached", "--ignore-unmatch", clean])
                .output();
            if let Ok(o) = output {
                if o.status.success() {
                    let stdout = String::from_utf8_lossy(&o.stdout);
                    count += stdout.lines().filter(|l| !l.is_empty()).count();
                }
            }
        }
    }
    Ok(count)
}

/// Return all paths under `pattern` that git currently tracks in the index.
fn resolve_tracked_paths(pattern: &str) -> Vec<String> {
    resolve_tracked_paths_in(pattern, None)
}

/// Inner implementation — `workdir` overrides CWD for testability.
fn resolve_tracked_paths_in(pattern: &str, workdir: Option<&Path>) -> Vec<String> {
    let mut cmd = Command::new("git");
    cmd.args(["ls-files", "--", pattern]);
    if let Some(dir) = workdir {
        cmd.current_dir(dir);
    }
    match cmd.output() {
        Ok(o) if o.status.success() => String::from_utf8_lossy(&o.stdout)
            .lines()
            .filter(|l| !l.is_empty())
            .map(|l| l.to_string())
            .collect(),
        _ => Vec::new(),
    }
}

/// Returns `true` if `path` appears in the commit history of the current branch.
fn is_file_tracked_in_history(path: &str) -> bool {
    is_file_tracked_in_history_in(path, None)
}

/// Inner implementation — `workdir` overrides CWD for testability.
fn is_file_tracked_in_history_in(path: &str, workdir: Option<&Path>) -> bool {
    let mut cmd = Command::new("git");
    // --no-pager: `git log` can invoke a pager when core.pager/GIT_PAGER
    // forces one, which blocks on a keypress read from the controlling
    // terminal rather than erroring out (see dispatch 479a4ab5 / the
    // identical fix in run.rs's git helpers).
    cmd.args(["--no-pager", "log", "--oneline", "-1", "--", path]);
    if let Some(dir) = workdir {
        cmd.current_dir(dir);
    }
    cmd.output()
        .map(|o| o.status.success() && !o.stdout.is_empty())
        .unwrap_or(false)
}

/// Run `git add` for each pattern that exists on disk.
fn retrack_patterns(patterns: &[&str]) -> anyhow::Result<usize> {
    let mut count = 0;
    for pat in patterns {
        let clean = pat.trim_end_matches('/');
        let path = Path::new(clean);
        if path.exists() {
            let output = Command::new("git").args(["add", clean]).output();
            if let Ok(o) = output {
                if o.status.success() {
                    count += 1;
                }
            }
        }
    }
    Ok(count)
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_remove_shadow_block() {
        let input = "# existing stuff\nfoo\n\n# >>> nexus shadow\n.claude/\nAGENTS.md\n# <<< nexus shadow\n\n# other stuff\nbar\n";
        let result = remove_block(input, MARKER_START, MARKER_END);
        assert!(result.contains("# existing stuff"));
        assert!(result.contains("# other stuff"));
        assert!(result.contains("bar"));
        assert!(!result.contains("nexus shadow"));
        assert!(!result.contains(".claude/"));
    }

    #[test]
    fn test_remove_shadow_block_only_block() {
        let input = "# >>> nexus shadow\n.claude/\n# <<< nexus shadow\n";
        let result = remove_block(input, MARKER_START, MARKER_END);
        assert!(result.is_empty());
    }

    #[test]
    fn test_remove_workspace_block() {
        let input = "# existing\n\n# >>> nexus workspace shadow\ndevbox.json\ndevbox.lock\n# <<< nexus workspace shadow\n\n# other\n";
        let result = remove_block(input, WS_MARKER_START, WS_MARKER_END);
        assert!(result.contains("# existing"));
        assert!(result.contains("# other"));
        assert!(!result.contains("devbox.json"));
        assert!(!result.contains("nexus workspace shadow"));
    }

    #[test]
    fn test_agentic_patterns_not_empty() {
        assert!(!AGENTIC_PATTERNS.is_empty());
        assert!(AGENTIC_PATTERNS.contains(&".claude/"));
        assert!(AGENTIC_PATTERNS.contains(&".taskmaster/"));
        assert!(AGENTIC_PATTERNS.contains(&".rtk/"));
        assert!(AGENTIC_PATTERNS.contains(&"RTK.md"));
        assert!(AGENTIC_PATTERNS.contains(&"taskmaster.config.yaml"));
    }

    #[test]
    fn test_workspace_patterns_not_empty() {
        assert!(!WORKSPACE_PATTERNS.is_empty());
        assert!(WORKSPACE_PATTERNS.contains(&"devbox.json"));
        assert!(WORKSPACE_PATTERNS.contains(&"devbox.lock"));
        assert!(WORKSPACE_PATTERNS.contains(&".devbox/"));
        assert!(WORKSPACE_PATTERNS.contains(&"scripts/devbox/"));
    }

    // ── Guard helper unit tests ──────────────────────────────────────────────

    /// `is_file_tracked_in_history` must return false for a path that has never
    /// been committed (we run against the current repo where this path does not
    /// exist as a committed file).
    #[test]
    fn test_is_file_tracked_in_history_unknown_path() {
        let result = is_file_tracked_in_history("__nexus_test_nonexistent_file_xyz__.txt");
        assert!(!result, "non-existent path must not appear in git history");
    }

    /// `resolve_tracked_paths` returns an empty vec for a pattern that matches
    /// nothing in the index.
    #[test]
    fn test_resolve_tracked_paths_no_match() {
        let paths = resolve_tracked_paths("__nexus_test_nonexistent_dir_xyz__/");
        assert!(
            paths.is_empty(),
            "no tracked paths expected for non-existent pattern"
        );
    }

    /// Helper: initialise a temp git repo with one committed file.
    /// Returns the tempdir (kept alive by caller) and the path.
    fn make_temp_repo_with_commit(filename: &str, content: &str) -> tempfile::TempDir {
        use std::process::Command;

        let dir = tempfile::tempdir().expect("tempdir");
        let path = dir.path();

        Command::new("git")
            .args(["init", "-b", "main"])
            .current_dir(path)
            .output()
            .unwrap();
        // Disable GPG signing for this repo regardless of the operator's
        // global git config: commit.gpgsign=true (common on dev machines)
        // makes `git commit` depend on gpg-agent, which can intermittently
        // stall/fail under concurrent test execution and has no bearing on
        // what these tests actually verify.
        Command::new("git")
            .args(["config", "commit.gpgsign", "false"])
            .current_dir(path)
            .output()
            .unwrap();
        std::fs::write(path.join(filename), content).unwrap();
        Command::new("git")
            .args(["add", filename])
            .current_dir(path)
            .output()
            .unwrap();
        Command::new("git")
            .args(["commit", "-m", "initial"])
            .current_dir(path)
            .env("GIT_AUTHOR_NAME", "Test")
            .env("GIT_AUTHOR_EMAIL", "test@test.com")
            .env("GIT_COMMITTER_NAME", "Test")
            .env("GIT_COMMITTER_EMAIL", "test@test.com")
            .output()
            .unwrap();
        dir
    }

    /// `is_file_tracked_in_history_in` returns true for a committed file.
    #[test]
    fn test_is_file_tracked_in_history_in_committed() {
        let dir = make_temp_repo_with_commit("shadow_test.txt", "hello");
        let result = is_file_tracked_in_history_in("shadow_test.txt", Some(dir.path()));
        assert!(result, "committed file must appear in git history");
    }

    /// `is_file_tracked_in_history_in` returns false for a staged-only file.
    #[test]
    fn test_is_file_tracked_in_history_in_staged_only() {
        use std::process::Command;

        let dir = make_temp_repo_with_commit("readme.txt", "root");
        let path = dir.path();

        // Add a second file but do not commit it
        std::fs::write(path.join("agentic.txt"), "agent").unwrap();
        Command::new("git")
            .args(["add", "agentic.txt"])
            .current_dir(path)
            .output()
            .unwrap();

        let result = is_file_tracked_in_history_in("agentic.txt", Some(path));
        assert!(!result, "staged-only file must not appear in git history");
    }

    /// `resolve_tracked_paths_in` finds staged files in the temp repo index.
    #[test]
    fn test_resolve_tracked_paths_in_finds_staged_file() {
        use std::process::Command;

        let dir = make_temp_repo_with_commit("readme.txt", "root");
        let path = dir.path();

        std::fs::write(path.join("agentic.txt"), "agent").unwrap();
        Command::new("git")
            .args(["add", "agentic.txt"])
            .current_dir(path)
            .output()
            .unwrap();

        let paths = resolve_tracked_paths_in("agentic.txt", Some(path));
        assert_eq!(paths, vec!["agentic.txt"]);
    }

    /// `untrack_patterns` skips a committed file — tested via the `_in` helpers
    /// to avoid set_current_dir (which is process-global and unsafe in parallel tests).
    #[test]
    fn test_guard_skips_committed_file() {
        let dir = make_temp_repo_with_commit("shadow_test.txt", "hello");
        let path = dir.path();

        // Verify the guard functions directly — committed file must be detected
        let tracked = resolve_tracked_paths_in("shadow_test.txt", Some(path));
        assert_eq!(tracked, vec!["shadow_test.txt"]);

        let has_history = is_file_tracked_in_history_in("shadow_test.txt", Some(path));
        assert!(
            has_history,
            "committed file must be detected as having history"
        );

        // File must still be on disk (untrack_patterns would have skipped it)
        assert!(path.join("shadow_test.txt").exists());
    }

    /// `untrack_patterns` removes a staged-only file — tested via `_in` helpers.
    #[test]
    fn test_guard_allows_staged_only_file() {
        use std::process::Command;

        let dir = make_temp_repo_with_commit("readme.txt", "root");
        let path = dir.path();

        std::fs::write(path.join("agentic.txt"), "agent").unwrap();
        Command::new("git")
            .args(["add", "agentic.txt"])
            .current_dir(path)
            .output()
            .unwrap();

        // Staged-only: in index, no history — guard must allow removal
        let tracked = resolve_tracked_paths_in("agentic.txt", Some(path));
        assert_eq!(tracked, vec!["agentic.txt"]);

        let has_history = is_file_tracked_in_history_in("agentic.txt", Some(path));
        assert!(
            !has_history,
            "staged-only file must not have history — guard must allow removal"
        );
    }

    fn git_repo(suffix: &str) -> PathBuf {
        let dir = std::env::temp_dir().join(format!(
            "nexus-shadow-server-{}-{}",
            std::process::id(),
            suffix
        ));
        let _ = fs::remove_dir_all(&dir);
        fs::create_dir_all(&dir).unwrap();
        let ok = Command::new("git")
            .args(["init", "-q"])
            .current_dir(&dir)
            .status()
            .unwrap()
            .success();
        assert!(ok);
        dir
    }

    fn exclude_of(dir: &Path) -> String {
        fs::read_to_string(dir.join(".git/info/exclude")).unwrap_or_default()
    }

    #[test]
    fn test_valid_exclude_path() {
        for ok in [
            ".claude/",
            ".nexus/",
            "AGENTS.md",
            ".nexus/claude/zellij.local.kdl",
            "*.log",
        ] {
            assert!(valid_exclude_path(ok), "{ok}");
        }
        for bad in [
            "",
            "  ",
            "/etc/passwd",
            "../x",
            "a/../../b",
            "!keep",
            "# c",
            "a\nb",
            "C:\\x",
            "a\\b",
        ] {
            assert!(!valid_exclude_path(bad), "{bad:?}");
        }
    }

    #[test]
    fn test_policy_value_maps_on_to_ai() {
        assert_eq!(policy_value("on"), Some("ai"));
        assert_eq!(policy_value("ai"), Some("ai"));
        assert_eq!(policy_value("nexus"), Some("nexus"));
        assert_eq!(policy_value("off"), Some("off"));
        assert_eq!(policy_value("status"), None);
    }

    #[test]
    fn test_apply_server_excludes_writes_and_replaces_block() {
        let dir = git_repo("block");
        fs::create_dir_all(dir.join(".git/info")).unwrap();
        fs::write(dir.join(".git/info/exclude"), "# user\n.env.nexus.local\n").unwrap();

        // shadow=ai: agentic paths plus personal files; one already listed
        // by the user stays outside the block, unsafe entries are refused.
        let paths: Vec<String> = [
            ".env.nexus.local",
            ".claude/",
            "AGENTS.md",
            "CLAUDE.md",
            "../evil",
            "!x",
        ]
        .iter()
        .map(|p| p.to_string())
        .collect();
        let report = apply_server_excludes(&dir, &paths);
        assert_eq!(report.added, vec![".claude/", "AGENTS.md", "CLAUDE.md"]);
        assert!(report.removed.is_empty());
        assert_eq!(report.rejected, vec!["../evil", "!x"]);
        let content = exclude_of(&dir);
        assert!(content.starts_with("# user\n.env.nexus.local\n"));
        assert_eq!(
            server_exclude_entries(&dir),
            vec![".claude/", "AGENTS.md", "CLAUDE.md"]
        );
        assert_eq!(content.matches(".env.nexus.local").count(), 1);

        // Idempotent.
        let again = apply_server_excludes(&dir, &paths);
        assert!(again.added.is_empty() && again.removed.is_empty());
        assert_eq!(exclude_of(&dir), content);

        // shadow=off: the agentic paths leave, the user's lines stay.
        let off = apply_server_excludes(&dir, &[".env.nexus.local".to_string()]);
        assert_eq!(off.removed, vec![".claude/", "AGENTS.md", "CLAUDE.md"]);
        assert_eq!(exclude_of(&dir), "# user\n.env.nexus.local\n");
        assert!(server_exclude_entries(&dir).is_empty());

        let _ = fs::remove_dir_all(&dir);
    }

    #[test]
    fn test_apply_server_excludes_reports_tracked_without_untracking() {
        let dir = git_repo("tracked");
        fs::write(dir.join("AGENTS.md"), "agents\n").unwrap();
        fs::create_dir_all(dir.join(".claude")).unwrap();
        fs::write(dir.join(".claude/settings.json"), "{}\n").unwrap();
        let ok = Command::new("git")
            .args(["add", "AGENTS.md", ".claude/settings.json"])
            .current_dir(&dir)
            .status()
            .unwrap()
            .success();
        assert!(ok);

        let paths: Vec<String> = ["AGENTS.md", ".claude/", "CLAUDE.md"]
            .iter()
            .map(|p| p.to_string())
            .collect();
        let report = apply_server_excludes(&dir, &paths);
        assert_eq!(report.tracked, vec!["AGENTS.md", ".claude/"]);
        // Still tracked: nothing was removed from the index.
        assert_eq!(
            resolve_tracked_paths_in("AGENTS.md", Some(&dir)),
            vec!["AGENTS.md"]
        );

        let _ = fs::remove_dir_all(&dir);
    }

    #[test]
    fn test_apply_server_excludes_outside_git_is_noop() {
        let dir = std::env::temp_dir().join(format!("nexus-shadow-nogit-{}", std::process::id()));
        let _ = fs::remove_dir_all(&dir);
        fs::create_dir_all(&dir).unwrap();
        // temp dirs are not inside a repo; if they were, skip silently.
        if find_git_dir_from(dir.clone()).is_err() {
            let report = apply_server_excludes(&dir, &[".claude/".to_string()]);
            assert_eq!(report, ServerExcludeReport::default());
        }
        let _ = fs::remove_dir_all(&dir);
    }
}
